clear all;close all; 
load('A_6_gauss.mat');
load('A_6_uniform.mat');
L = 2;
a = [6 12 18];
var_ = [4 8 12];
%% semilogy results
xvector = [1:L];
% high video
figure('Name','PSNR for high video');
semilogy(var_,q6_gauss(1:3,1),'-+',a,q6_uniform(1:3,1),'-+',...
         var_,q6_gauss(4:6,1),'-+',a,q6_uniform(4:6,1),'-+',...
         var_,q6_gauss(1:3,2),'-+',a,q6_uniform(1:3,2),'-+',...
         var_,q6_gauss(4:6,2),'-+',a,q6_uniform(4:6,2),'-+');
ylabel('PSNR_(dB)');xlabel('Variance');
title('PSNR for high video');
legend('High\_1\_ECC\_gauss','High\_1\_ECC\_uniform', ...
        'High\_2\_ECC\_gauss','High\_2\_ECC\_uniform', ...
        'High\_1\_LK\_gauss','High\_1\_LK\_uniform', ...
        'High\_2\_LK\_gauss','High\_2\_ECC\_uniform');
%low video
figure('Name','PSNR for low video');
semilogy(var_,q6_gauss(1:3,3),'-+',a,q6_uniform(1:3,3),'-+',...
         var_,q6_gauss(4:6,3),'-+',a,q6_uniform(4:6,3),'-+',...
         var_,q6_gauss(1:3,4),'-+',a,q6_uniform(1:3,4),'-+',...
         var_,q6_gauss(4:6,4),'-+',a,q6_uniform(4:6,4),'-+');
ylabel('PSNR_(dB)');xlabel('Variance');
title('PSNR for high video');
legend('Low\_1\_ECC\_gauss','Low\_1\_ECC\_uniform', ...
        'Low\_2\_ECC\_gauss','Low\_2\_ECC\_uniform', ...
        'Low\_1\_LK\_gauss','Low\_1\_LK\_uniform', ...
        'Low\_2\_LK\_gauss','Low\_2\_ECC\_uniform');






